from PyQt5 import QtCore, QtWidgets

def create_tab(panel):
    """「クロスヘア」タブを生成する"""
    ch_tab = QtWidgets.QWidget()
    ch_layout = QtWidgets.QVBoxLayout(ch_tab)
    ch_layout.setContentsMargins(10, 15, 10, 10)
    ch_layout.setSpacing(12)

    panel.crosshair_btn = QtWidgets.QCheckBox("クロスヘアを表示")
    panel.crosshair_btn.toggled.connect(panel.toggle_crosshair_button)
    ch_layout.addWidget(panel.crosshair_btn)

    shape_layout = QtWidgets.QHBoxLayout()
    panel.shape_box = QtWidgets.QComboBox()
    panel.shape_box.currentTextChanged.connect(panel.update_crosshair_shape)
    shape_layout.addWidget(QtWidgets.QLabel("形状:"))
    shape_layout.addWidget(panel.shape_box, 1)
    ch_layout.addLayout(shape_layout)

    # --- アドバンスド設定 --- #
    # これは十字と円の設定を含むコンテナ
    panel.advanced_settings_group = QtWidgets.QGroupBox()
    panel.advanced_settings_group.setContentsMargins(0, 0, 0, 0)
    advanced_container_layout = QtWidgets.QVBoxLayout(panel.advanced_settings_group)
    advanced_container_layout.setContentsMargins(10, 10, 10, 10)
    advanced_container_layout.setSpacing(10)

    # --- 十字アドバンスド設定ウィジェット ---
    panel.cross_settings_widget = QtWidgets.QWidget()
    cross_advanced_layout = QtWidgets.QFormLayout(panel.cross_settings_widget)
    cross_advanced_layout.setContentsMargins(0, 0, 0, 0)
    cross_advanced_layout.setSpacing(10)

    panel.outline_btn = QtWidgets.QCheckBox("輪郭")
    panel.outline_btn.toggled.connect(panel.update_outline_enabled)
    cross_advanced_layout.addRow(panel.outline_btn)

    panel.outline_width_slider = QtWidgets.QSlider(QtCore.Qt.Horizontal)
    panel.outline_width_slider.setRange(1, 6)
    panel.outline_width_slider.valueChanged.connect(panel.update_outline_width)
    panel.outline_width_edit = QtWidgets.QLineEdit()
    panel.outline_width_edit.setFixedWidth(45)
    outline_width_layout = QtWidgets.QHBoxLayout()
    outline_width_layout.addWidget(panel.outline_width_slider)
    outline_width_layout.addWidget(panel.outline_width_edit)
    cross_advanced_layout.addRow("輪郭の太さ:", outline_width_layout)

    panel.crosshair_outline_alpha_slider = QtWidgets.QSlider(QtCore.Qt.Horizontal)
    panel.crosshair_outline_alpha_slider.setRange(0, 100)
    panel.crosshair_outline_alpha_slider.valueChanged.connect(panel.update_crosshair_outline_alpha)
    panel.crosshair_outline_alpha_edit = QtWidgets.QLineEdit()
    panel.crosshair_outline_alpha_edit.setFixedWidth(45)
    crosshair_outline_alpha_layout = QtWidgets.QHBoxLayout()
    crosshair_outline_alpha_layout.addWidget(panel.crosshair_outline_alpha_slider)
    crosshair_outline_alpha_layout.addWidget(panel.crosshair_outline_alpha_edit)
    cross_advanced_layout.addRow("輪郭の透明度:", crosshair_outline_alpha_layout)

    panel.vline_length_slider = QtWidgets.QSlider(QtCore.Qt.Horizontal)
    panel.vline_length_slider.setRange(0, 20)
    panel.vline_length_slider.valueChanged.connect(panel.update_vline_length)
    panel.vline_length_edit = QtWidgets.QLineEdit()
    panel.vline_length_edit.setFixedWidth(45)
    vline_length_layout = QtWidgets.QHBoxLayout()
    vline_length_layout.addWidget(panel.vline_length_slider)
    vline_length_layout.addWidget(panel.vline_length_edit)
    cross_advanced_layout.addRow("縦線の長さ:", vline_length_layout)

    panel.hline_length_slider = QtWidgets.QSlider(QtCore.Qt.Horizontal)
    panel.hline_length_slider.setRange(0, 20)
    panel.hline_length_slider.valueChanged.connect(panel.update_hline_length)
    panel.hline_length_edit = QtWidgets.QLineEdit()
    panel.hline_length_edit.setFixedWidth(45)
    hline_length_layout = QtWidgets.QHBoxLayout()
    hline_length_layout.addWidget(panel.hline_length_slider)
    hline_length_layout.addWidget(panel.hline_length_edit)
    cross_advanced_layout.addRow("横線の長さ:", hline_length_layout)

    panel.line_thickness_slider = QtWidgets.QSlider(QtCore.Qt.Horizontal)
    panel.line_thickness_slider.setRange(0, 10)
    panel.line_thickness_slider.valueChanged.connect(panel.update_line_thickness)
    panel.line_thickness_edit = QtWidgets.QLineEdit()
    panel.line_thickness_edit.setFixedWidth(45)
    line_thickness_layout = QtWidgets.QHBoxLayout()
    line_thickness_layout.addWidget(panel.line_thickness_slider)
    line_thickness_layout.addWidget(panel.line_thickness_edit)
    cross_advanced_layout.addRow("線の太さ:", line_thickness_layout)

    panel.crosshair_inner_alpha_slider = QtWidgets.QSlider(QtCore.Qt.Horizontal)
    panel.crosshair_inner_alpha_slider.setRange(0, 100)
    panel.crosshair_inner_alpha_slider.valueChanged.connect(panel.update_crosshair_inner_alpha)
    panel.crosshair_inner_alpha_edit = QtWidgets.QLineEdit()
    panel.crosshair_inner_alpha_edit.setFixedWidth(45)
    crosshair_inner_alpha_layout = QtWidgets.QHBoxLayout()
    crosshair_inner_alpha_layout.addWidget(panel.crosshair_inner_alpha_slider)
    crosshair_inner_alpha_layout.addWidget(panel.crosshair_inner_alpha_edit)
    cross_advanced_layout.addRow("内側の透明度:", crosshair_inner_alpha_layout)

    panel.gap_slider = QtWidgets.QSlider(QtCore.Qt.Horizontal)
    panel.gap_slider.setRange(0, 20)
    panel.gap_slider.valueChanged.connect(panel.update_gap)
    panel.gap_edit = QtWidgets.QLineEdit()
    panel.gap_edit.setFixedWidth(45)
    gap_layout = QtWidgets.QHBoxLayout()
    gap_layout.addWidget(panel.gap_slider)
    gap_layout.addWidget(panel.gap_edit)
    cross_advanced_layout.addRow("ギャップ:", gap_layout)

    # --- ここから外枠の設定 ---
    panel.outer_line_btn = QtWidgets.QCheckBox("外枠")
    panel.outer_line_btn.toggled.connect(panel.update_outer_line_enabled)
    cross_advanced_layout.addRow(panel.outer_line_btn)

    panel.outer_vline_length_slider = QtWidgets.QSlider(QtCore.Qt.Horizontal)
    panel.outer_vline_length_slider.setRange(0, 10)
    panel.outer_vline_length_slider.valueChanged.connect(panel.update_outer_vline_length)
    panel.outer_vline_length_edit = QtWidgets.QLineEdit()
    panel.outer_vline_length_edit.setFixedWidth(45)
    outer_vline_length_layout = QtWidgets.QHBoxLayout()
    outer_vline_length_layout.addWidget(panel.outer_vline_length_slider)
    outer_vline_length_layout.addWidget(panel.outer_vline_length_edit)
    cross_advanced_layout.addRow("外枠の縦線の長さ:", outer_vline_length_layout)

    panel.outer_hline_length_slider = QtWidgets.QSlider(QtCore.Qt.Horizontal)
    panel.outer_hline_length_slider.setRange(0, 10)
    panel.outer_hline_length_slider.valueChanged.connect(panel.update_outer_hline_length)
    panel.outer_hline_length_edit = QtWidgets.QLineEdit()
    panel.outer_hline_length_edit.setFixedWidth(45)
    outer_hline_length_layout = QtWidgets.QHBoxLayout()
    outer_hline_length_layout.addWidget(panel.outer_hline_length_slider)
    outer_hline_length_layout.addWidget(panel.outer_hline_length_edit)
    cross_advanced_layout.addRow("外枠の横線の長さ:", outer_hline_length_layout)

    panel.outer_line_alpha_slider = QtWidgets.QSlider(QtCore.Qt.Horizontal)
    panel.outer_line_alpha_slider.setRange(0, 100)
    panel.outer_line_alpha_slider.valueChanged.connect(panel.update_outer_line_alpha)
    panel.outer_line_alpha_edit = QtWidgets.QLineEdit()
    panel.outer_line_alpha_edit.setFixedWidth(45)
    outer_line_alpha_layout = QtWidgets.QHBoxLayout()
    outer_line_alpha_layout.addWidget(panel.outer_line_alpha_slider)
    outer_line_alpha_layout.addWidget(panel.outer_line_alpha_edit)
    cross_advanced_layout.addRow("外枠の透明度:", outer_line_alpha_layout)

    panel.outer_line_thickness_slider = QtWidgets.QSlider(QtCore.Qt.Horizontal)
    panel.outer_line_thickness_slider.setRange(0, 10)
    panel.outer_line_thickness_slider.valueChanged.connect(panel.update_outer_line_thickness)
    panel.outer_line_thickness_edit = QtWidgets.QLineEdit()
    panel.outer_line_thickness_edit.setFixedWidth(45)
    outer_line_thickness_layout = QtWidgets.QHBoxLayout()
    outer_line_thickness_layout.addWidget(panel.outer_line_thickness_slider)
    outer_line_thickness_layout.addWidget(panel.outer_line_thickness_edit)
    cross_advanced_layout.addRow("外枠の太さ:", outer_line_thickness_layout)

    panel.outer_gap_slider = QtWidgets.QSlider(QtCore.Qt.Horizontal)
    panel.outer_gap_slider.setRange(0, 20)
    panel.outer_gap_slider.valueChanged.connect(panel.update_outer_gap)
    panel.outer_gap_edit = QtWidgets.QLineEdit()
    panel.outer_gap_edit.setFixedWidth(45)
    outer_gap_layout = QtWidgets.QHBoxLayout()
    outer_gap_layout.addWidget(panel.outer_gap_slider)
    outer_gap_layout.addWidget(panel.outer_gap_edit)
    cross_advanced_layout.addRow("外枠のギャップ:", outer_gap_layout)
    # --- ここまで外枠の設定 ---

    advanced_container_layout.addWidget(panel.cross_settings_widget)

    # --- 円アドバンスド設定ウィジェット ---
    panel.circle_settings_widget = QtWidgets.QWidget()
    circle_advanced_layout = QtWidgets.QFormLayout(panel.circle_settings_widget)
    circle_advanced_layout.setContentsMargins(0, 0, 0, 0)
    circle_advanced_layout.setSpacing(10)

    panel.circle_outline_btn = QtWidgets.QCheckBox("輪郭")
    panel.circle_outline_btn.toggled.connect(panel.update_circle_outline_enabled)
    circle_advanced_layout.addRow(panel.circle_outline_btn)

    panel.circle_outline_width_slider = QtWidgets.QSlider(QtCore.Qt.Horizontal)
    panel.circle_outline_width_slider.setRange(1, 6)
    panel.circle_outline_width_slider.valueChanged.connect(panel.update_circle_outline_width)
    panel.circle_outline_width_edit = QtWidgets.QLineEdit()
    panel.circle_outline_width_edit.setFixedWidth(45)
    circle_outline_width_layout = QtWidgets.QHBoxLayout()
    circle_outline_width_layout.addWidget(panel.circle_outline_width_slider)
    circle_outline_width_layout.addWidget(panel.circle_outline_width_edit)
    circle_advanced_layout.addRow("輪郭の太さ:", circle_outline_width_layout)

    panel.circle_outline_alpha_slider = QtWidgets.QSlider(QtCore.Qt.Horizontal)
    panel.circle_outline_alpha_slider.setRange(0, 100)
    panel.circle_outline_alpha_slider.valueChanged.connect(panel.update_circle_outline_alpha)
    panel.circle_outline_alpha_edit = QtWidgets.QLineEdit()
    panel.circle_outline_alpha_edit.setFixedWidth(45)
    circle_outline_alpha_layout = QtWidgets.QHBoxLayout()
    circle_outline_alpha_layout.addWidget(panel.circle_outline_alpha_slider)
    circle_outline_alpha_layout.addWidget(panel.circle_outline_alpha_edit)
    circle_advanced_layout.addRow("輪郭の透明度:", circle_outline_alpha_layout)

    panel.circle_thickness_slider = QtWidgets.QSlider(QtCore.Qt.Horizontal)
    panel.circle_thickness_slider.setRange(0, 20)
    panel.circle_thickness_slider.valueChanged.connect(panel.update_circle_thickness)
    panel.circle_thickness_edit = QtWidgets.QLineEdit()
    panel.circle_thickness_edit.setFixedWidth(45)
    circle_thickness_layout = QtWidgets.QHBoxLayout()
    circle_thickness_layout.addWidget(panel.circle_thickness_slider)
    circle_thickness_layout.addWidget(panel.circle_thickness_edit)
    circle_advanced_layout.addRow("線の太さ:", circle_thickness_layout)

    panel.circle_diameter_slider = QtWidgets.QSlider(QtCore.Qt.Horizontal)
    panel.circle_diameter_slider.setRange(0, 100)
    panel.circle_diameter_slider.valueChanged.connect(panel.update_circle_diameter)
    panel.circle_diameter_edit = QtWidgets.QLineEdit()
    panel.circle_diameter_edit.setFixedWidth(45)
    circle_diameter_layout = QtWidgets.QHBoxLayout()
    circle_diameter_layout.addWidget(panel.circle_diameter_slider)
    circle_diameter_layout.addWidget(panel.circle_diameter_edit)
    circle_advanced_layout.addRow("円の直径:", circle_diameter_layout)

    advanced_container_layout.addWidget(panel.circle_settings_widget)

    # --- 矢印 (シェブロン) アドバンスド設定ウィジェット ---
    panel.chevron_settings_widget = QtWidgets.QWidget()
    chevron_advanced_layout = QtWidgets.QFormLayout(panel.chevron_settings_widget)
    chevron_advanced_layout.setContentsMargins(0, 0, 0, 0)
    chevron_advanced_layout.setSpacing(10)

    panel.chevron_outline_btn = QtWidgets.QCheckBox("輪郭")
    panel.chevron_outline_btn.toggled.connect(panel.update_chevron_outline_enabled)
    chevron_advanced_layout.addRow(panel.chevron_outline_btn)

    panel.chevron_outline_width_slider = QtWidgets.QSlider(QtCore.Qt.Horizontal)
    panel.chevron_outline_width_slider.setRange(1, 6)
    panel.chevron_outline_width_slider.valueChanged.connect(panel.update_chevron_outline_width)
    panel.chevron_outline_width_edit = QtWidgets.QLineEdit()
    panel.chevron_outline_width_edit.setFixedWidth(45)
    chevron_outline_width_layout = QtWidgets.QHBoxLayout()
    chevron_outline_width_layout.addWidget(panel.chevron_outline_width_slider)
    chevron_outline_width_layout.addWidget(panel.chevron_outline_width_edit)
    chevron_advanced_layout.addRow("輪郭の太さ:", chevron_outline_width_layout)

    panel.chevron_outline_alpha_slider = QtWidgets.QSlider(QtCore.Qt.Horizontal)
    panel.chevron_outline_alpha_slider.setRange(0, 100)
    panel.chevron_outline_alpha_slider.valueChanged.connect(panel.update_chevron_outline_alpha)
    panel.chevron_outline_alpha_edit = QtWidgets.QLineEdit()
    panel.chevron_outline_alpha_edit.setFixedWidth(45)
    chevron_outline_alpha_layout = QtWidgets.QHBoxLayout()
    chevron_outline_alpha_layout.addWidget(panel.chevron_outline_alpha_slider)
    chevron_outline_alpha_layout.addWidget(panel.chevron_outline_alpha_edit)
    chevron_advanced_layout.addRow("輪郭の透明度:", chevron_outline_alpha_layout)

    panel.chevron_thickness_slider = QtWidgets.QSlider(QtCore.Qt.Horizontal)
    panel.chevron_thickness_slider.setRange(0, 20)
    panel.chevron_thickness_slider.valueChanged.connect(panel.update_chevron_thickness)
    panel.chevron_thickness_edit = QtWidgets.QLineEdit()
    panel.chevron_thickness_edit.setFixedWidth(45)
    chevron_thickness_layout = QtWidgets.QHBoxLayout()
    chevron_thickness_layout.addWidget(panel.chevron_thickness_slider)
    chevron_thickness_layout.addWidget(panel.chevron_thickness_edit)
    chevron_advanced_layout.addRow("線の太さ:", chevron_thickness_layout)

    panel.chevron_length_slider = QtWidgets.QSlider(QtCore.Qt.Horizontal)
    panel.chevron_length_slider.setRange(1, 40)
    panel.chevron_length_slider.valueChanged.connect(panel.update_chevron_length)
    panel.chevron_length_edit = QtWidgets.QLineEdit()
    panel.chevron_length_edit.setFixedWidth(45)
    chevron_length_layout = QtWidgets.QHBoxLayout()
    chevron_length_layout.addWidget(panel.chevron_length_slider)
    chevron_length_layout.addWidget(panel.chevron_length_edit)
    chevron_advanced_layout.addRow("線の長さ:", chevron_length_layout)

    advanced_container_layout.addWidget(panel.chevron_settings_widget)

    # --- 画像系アドバンスド設定ウィジェット ---
    panel.image_settings_widget = QtWidgets.QWidget()
    image_advanced_layout = QtWidgets.QFormLayout(panel.image_settings_widget)
    image_advanced_layout.setContentsMargins(0, 0, 0, 0)
    image_advanced_layout.setSpacing(10)

    panel.image_crosshair_size_slider = QtWidgets.QSlider(QtCore.Qt.Horizontal)
    panel.image_crosshair_size_slider.setRange(0, 100)
    panel.image_crosshair_size_slider.valueChanged.connect(panel.update_image_crosshair_size)
    panel.image_crosshair_size_edit = QtWidgets.QLineEdit()
    panel.image_crosshair_size_edit.setFixedWidth(45)
    image_crosshair_size_layout = QtWidgets.QHBoxLayout()
    image_crosshair_size_layout.addWidget(panel.image_crosshair_size_slider)
    image_crosshair_size_layout.addWidget(panel.image_crosshair_size_edit)
    image_advanced_layout.addRow("リサイズ:", image_crosshair_size_layout)

    advanced_container_layout.addWidget(panel.image_settings_widget)

    # --- 折りたたみ可能なアドバンスド設定のセットアップ ---
    collapsible_advanced_layout = QtWidgets.QVBoxLayout()
    collapsible_advanced_layout.setContentsMargins(0, 0, 0, 0)

    panel.advanced_settings_toggle_btn = QtWidgets.QToolButton()
    panel.advanced_settings_toggle_btn.setText("アドバンスド設定")
    panel.advanced_settings_toggle_btn.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
    panel.advanced_settings_toggle_btn.setArrowType(QtCore.Qt.RightArrow)
    panel.advanced_settings_toggle_btn.setCheckable(True)
    panel.advanced_settings_toggle_btn.setChecked(False)
    panel.advanced_settings_toggle_btn.toggled.connect(panel.advanced_settings_group.setVisible)

    def rotate_arrow(checked):
        panel.advanced_settings_toggle_btn.setArrowType(QtCore.Qt.DownArrow if checked else QtCore.Qt.RightArrow)
    panel.advanced_settings_toggle_btn.toggled.connect(rotate_arrow)

    collapsible_advanced_layout.addWidget(panel.advanced_settings_toggle_btn)
    collapsible_advanced_layout.addWidget(panel.advanced_settings_group)

    panel.advanced_settings_group.setVisible(False)

    ch_layout.addLayout(collapsible_advanced_layout)

    # --- その他のUI要素 ---
    panel.custom_image_widget = QtWidgets.QWidget()
    custom_image_layout = QtWidgets.QHBoxLayout(panel.custom_image_widget)
    custom_image_layout.setContentsMargins(0, 5, 0, 0)
    select_image_btn = QtWidgets.QPushButton("画像を選択...")
    select_image_btn.clicked.connect(panel.select_custom_image)
    panel.custom_image_path_label = QtWidgets.QLabel("選択されていません")
    panel.custom_image_path_label.setWordWrap(True)
    custom_image_layout.addWidget(select_image_btn)
    custom_image_layout.addWidget(panel.custom_image_path_label, 1)
    ch_layout.addWidget(panel.custom_image_widget)

    panel.ch_color_widget = QtWidgets.QWidget()
    ch_color_layout, panel.ch_color_square = panel.make_color_button("色:", lambda: panel.overlay.crosshair_color, panel.set_crosshair_color, lambda: panel.overlay.update())
    ch_color_layout.setContentsMargins(0, 0, 0, 0)
    panel.ch_color_widget.setLayout(ch_color_layout)
    ch_layout.addWidget(panel.ch_color_widget)

    alpha_layout = QtWidgets.QHBoxLayout()
    panel.alpha_slider = QtWidgets.QSlider(QtCore.Qt.Horizontal)
    panel.alpha_slider.setRange(0, 100)
    panel.alpha_value_edit = QtWidgets.QLineEdit()
    panel.alpha_value_edit.setFixedWidth(45)
    panel.alpha_slider.valueChanged.connect(panel.update_alpha)
    alpha_layout.addWidget(QtWidgets.QLabel("透明度:"))
    alpha_layout.addWidget(panel.alpha_slider)
    alpha_layout.addWidget(panel.alpha_value_edit)
    ch_layout.addLayout(alpha_layout)

    ch_layout.addStretch()

    return ch_tab